<%@ Page Title="" Language="C#" MasterPageFile="~/Masterpage/Main.Master" AutoEventWireup="true" CodeBehind="AddMedicine.aspx.cs" Inherits="NorthBay.Web.Admin.Pharmacy.AddMedicine" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<h2> Add Medicine</h2>

  <br />
  <br />

     <asp:Label ID="lblError" runat="server" Font-Bold="True" ForeColor="#6600CC"></asp:Label>

       <br />
  <br />

    <asp:Label ID="lblName" runat="server" Font-Bold="true" Text="Name"></asp:Label>
    <br />
    <asp:TextBox ID="txtName" runat="server"></asp:TextBox><br /><br />

     <asp:Label ID="lblDescription" runat="server" Font-Bold="true" Text="Description"></asp:Label><br />
    <asp:TextBox ID="txtDescription" TextMode="MultiLine" runat="server" 
        Height="125px" Width="210px"></asp:TextBox><br /><br />  
          

    <asp:Label ID="lblPrice" runat="server" Font-Bold="true" Text="Price"></asp:Label><br />
    <asp:TextBox ID="txtPrice" runat="server"></asp:TextBox><br /><br /> 

    <asp:Label ID="lblStock" runat="server" Font-Bold="true" Text="Stock"></asp:Label><br />
    <asp:TextBox ID="txtStock" runat="server"></asp:TextBox><br /><br />

    <asp:Label ID="lblCategory" runat="server" Font-Bold="true" Text="Category"></asp:Label>
    <custom:DropDownList runat="server" ID="ddl_category" Required="True" Title="Category"> 
                                </custom:DropDownList>
                                <br />

    <asp:Label ID="lblActive" runat="server" Font-Bold="true" Text="Active"></asp:Label>
    
                        <custom:DropDownList runat="server" ID="ddl_active" Required="True">
                            <items>
                                <asp:ListItem Text="Yes" Value="True"></asp:ListItem>
                                <asp:ListItem Text="No" Value="False"></asp:ListItem>
                            </items>
                        </custom:DropDownList>
                    <br />

    <asp:Button ID="btnAdd" runat="server" Text="Add" onclick="btnAdd_Click" />
    <br />
      <asp:Button ID="btnUpdate" runat="server" Text="Update" Visible="false" 
        onclick="btnUpdate_Click" /> &nbsp;&nbsp;
    <asp:Button ID="btnCancel" runat="server" Text="Cancel" Visible="false" 
        onclick="btnCancel_Click" />

    <br />
    <br />


    <asp:GridView ID="gridView" DataKeyNames="Id" 
      AutoGenerateDeleteButton="True" onrowdeleting="GridViewResult_RowDeleting" 
     onselectedindexchanged="GridViewResult_SelectedIndexChanged" 
     AutoGenerateEditButton="True"
     onrowediting="GridViewResult_RowEditing"
     runat="server">
    </asp:GridView>
</asp:Content>
